---
title: "lunkenheimer_06"
author: "Hannah Lunkenheimer"
date: "`r Sys.Date()`"
output: html_document
---

# Info here

The NBA season for the 2021-2022 year ran from Oct 19, 2021 – Jun 18, 2022. This data is from 4/1/2021 to 6/30/2022.

```{r setup, include=FALSE, message=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(include=TRUE, message=FALSE, echo=TRUE, warning=FALSE)


library(dplyr)
library(lubridate)
library(ggplot2)
library(anytime)
library(ggimage)
library(readr)
#d_all <- read_csv("~/PycharmProjects/liwc/G:\\hannahlunkenheimer\\PycharmProjects\\liwc\\2022nbafinalswarriors.#csv")
#
#d_all <- d_all[!(d_all$author=="[deleted]"),]
#d_all <- d_all[!(d_all$author=="[removed]"),]
#
#d_all$created_utc= as.numeric(d_all$created_utc)
#d_all$created_utc=anytime(d_all$created_utc,asUTC=TRUE)
#d_all$created_utc<- as.Date(d_all$created_utc)
#
#write.csv(d_all,"~/PycharmProjects/liwc/G:\\hannahlunkenheimer\\PycharmProjects\\liwc\\2022nbawarriors.csv", row.names = FALSE)

```

```{r liwc data}
d_all <- read_csv("~/PycharmProjects/liwc/LIWC-22 Results - G:\\hannahlunkenheimer\\PycharmP___ - LIWC Analysis.csv")

d_all <- subset(d_all, WC>20) 

#gsub("(http|www)\\S+", "", d_all)


#Remove texts with [deleted] users or [removed] content
#Choose some sort of word count cutoff (e.g. 25 words)
#Clean up things like hyperlinks
```

```{r time series dataframes}
d_season <- d_all[d_all$created_utc >= "2021-10-10" & d_all$created_utc <= "2022-06-20", ]
d_season$month <- floor_date(d_season$created_utc, "month")
d_season$week <- floor_date(d_season$created_utc, "week")
d_season$day <- floor_date(d_season$created_utc, "day")

d_playoffs <- d_all[d_all$created_utc >= "2022-04-16" & d_all$created_utc <= "2022-06-20", ]
d_playoffs$week <- floor_date(d_playoffs$created_utc, "week")
d_playoffs$day <- floor_date(d_playoffs$created_utc, "day")



d_finals <- d_all[d_all$created_utc >= "2022-06-02" & d_all$created_utc <= "2022-06-18", ]
d_finals$day <- floor_date(d_finals$created_utc, "day")
#seeing the day means 
d_finals %>%
  group_by(day) %>%
  summarize(mean = mean(Analytic))

d_game1 <- d_all[d_all$created_utc >= "2022-06-02" & d_all$created_utc <= "2022-06-03", ]
d_game1$hour <- floor_date(d_game1$created_utc, "hour")
```

```{r adding wins and losses to the season}
# adding wins and losses to the dataset?
d_season$outcome <- as.character(d_season$day)
d_season$season <- as.character(d_season$day)

#d_season$outcome <- recode(d_season$outcome, "2022-06-19" = "Off","2022-06-18" = "Off", #"2022-06-17" = "Off","2022-06-15" = "Off", "2022-06-14" = "Off", )
d_season$outcome <- recode(d_season$outcome, "2022-06-16" = "Win", "2022-06-13" = "Win", "2022-06-10" = "Win", "2022-06-05" = "Win", "2022-05-26" = "Win", "2022-05-22" = "Win", "2022-05-20" = "Win", "2022-05-18" = "Win", "2022-05-13" = "Win", "2022-05-09" = "Win", "2022-05-07" = "Win", "2022-05-01" = "Win", "2022-04-27" = "Win", "2022-04-21" = "Win", "2022-04-18" = "Win", "2022-04-16" = "Win", "2022-04-10" = "Win", "2022-04-09" = "Win", "2022-04-07" = "Win", "2022-04-03" = "Win", "2022-04-02" = "Win", "2022-03-23" = "Win", "2022-03-14" = "Win", "2022-03-12" = "Win", "2022-03-10" = "Win", "2022-03-08" = "Win", "2022-02-24" = "Win", "2022-02-12" = "Win", "2022-02-07" = "Win", "2022-02-03" = "Win", "2022-02-01" = "Win", "2022-01-31" = "Win", "2022-01-29" = "Win", "2022-01-27" = "Win", "2022-01-25" = "Win", "2022-01-23" = "Win", "2022-01-21" = "Win", "2022-01-18" = "Win", "2022-01-14" = "Win", "2022-01-09" = "Win", "2022-01-03" = "Win", "2022-01-01" = "Win", "2021-12-25" = "Win", "2021-12-23" = "Win", "2021-12-20" = "Win", "2021-12-17" = "Win", "2021-12-14" = "Win", "2021-12-13" = "Win", "2021-12-08" = "Win", "2021-12-06" = "Win", "2021-12-03" = "Win", "2021-11-28" = "Win", "2021-11-26" = "Win", "2021-11-24" = "Win", "2021-11-21" = "Win", "2021-11-19" = "Win", "2021-11-18" = "Win", "2021-11-16" = "Win", "2021-11-12" = "Win", "2021-11-10" = "Win", "2021-11-08" = "Win", "2021-11-07" = "Win", "2021-11-05" = "Win", "2021-11-03" = "Win", "2021-10-30" = "Win", "2021-10-26" = "Win", "2021-10-24" = "Win", "2021-10-21" = "Win", "2021-10-19" = "Win")

d_season$outcome <- recode(d_season$outcome, "2022-06-08" = "Loss", "2022-06-02" = "Loss", "2022-05-24" = "Loss", "2022-05-11" = "Loss", "2022-05-03" = "Loss","2022-04-24" = "Loss", "2022-03-30" = "Loss", "2022-03-28" = "Loss", "2022-03-27" = "Loss", "2022-03-25" = "Loss", "2022-03-22" = "Loss", "2022-03-20" = "Loss", "2022-03-16" = "Loss", "2022-03-07" = "Loss", "2022-03-05" = "Loss", "2022-03-03" = "Loss", "2022-03-01" = "Loss", "2022-02-27" = "Loss", "2022-02-16" = "Loss", "2022-02-14" = "Loss", "2022-02-10" = "Loss", "2022-02-09" = "Loss", "2022-01-20" = "Loss", "2022-01-16" = "Loss", "2022-01-13" = "Loss", "2022-01-11" = "Loss", "2022-01-06" = "Loss", "2022-01-05" = "Loss", "2021-12-28" = "Loss", "2021-12-18" = "Loss", "2021-12-11" = "Loss", "2021-12-04" = "Loss", "2021-11-30" = "Loss", "2021-11-14" = "Loss", "2021-10-28" = "Loss") 

d_season$outcome <- recode(d_season$outcome, "2021-10-10" = "Off", "2021-10-11" = "Off", "2021-10-12" = "Off", "2021-10-13" = "Off", "2021-10-14" = "Off", "2021-10-15" = "Off", "2021-10-16" = "Off", "2021-10-17" = "Off", "2021-10-18" = "Off", "2021-10-20" = "Off", "2021-10-22" = "Off", "2021-10-23" = "Off", "2021-10-25" = "Off", "2021-10-27" = "Off", "2021-10-29" = "Off", "2021-10-31" = "Off", "2021-11-01" = "Off", "2021-11-02" = "Off", "2021-11-04" = "Off", "2021-11-06" = "Off", "2021-11-09" = "Off", "2021-11-11" = "Off", "2021-11-13" = "Off", "2021-11-15" = "Off", "2021-11-17" = "Off", "2021-11-20" = "Off", "2021-11-22" = "Off", "2021-11-23" = "Off", "2021-11-25" = "Off", "2021-11-27" = "Off", "2021-11-29" = "Off", "2021-12-01" = "Off", "2021-12-02" = "Off", "2021-12-05" = "Off", "2021-12-07" = "Off", "2021-12-09" = "Off", "2021-12-10" = "Off", "2021-12-12" = "Off", "2021-12-15" = "Off", "2021-12-16" = "Off", "2021-12-19" = "Off", "2021-12-21" = "Off", "2021-12-22" = "Off", "2021-12-24" = "Off", "2021-12-26" = "Off", "2021-12-27" = "Off", "2021-12-29" = "Off", "2021-12-30" = "Off", "2021-12-31" = "Off", "2022-01-02" = "Off", "2022-01-04" = "Off", "2022-01-07" = "Off", "2022-01-08" = "Off", "2022-01-10" = "Off", "2022-01-12" = "Off", "2022-01-15" = "Off", "2022-01-17" = "Off", "2022-01-19" = "Off", "2022-01-22" = "Off", "2022-01-24" = "Off", "2022-01-26" = "Off", "2022-01-28" = "Off", "2022-01-30" = "Off", "2022-02-02" = "Off", "2022-02-04" = "Off", "2022-02-05" = "Off", "2022-02-06" = "Off", "2022-02-08" = "Off", "2022-02-11" = "Off", "2022-02-13" = "Off", "2022-02-15" = "Off", "2022-02-17" = "Off", "2022-02-18" = "Off", "2022-02-19" = "Off", "2022-02-20" = "Off", "2022-02-21" = "Off", "2022-02-22" = "Off", "2022-02-23" = "Off", "2022-02-25" = "Off", "2022-02-26" = "Off", "2022-02-28" = "Off", "2022-03-02" = "Off", "2022-03-04" = "Off", "2022-03-06" = "Off", "2022-03-09" = "Off", "2022-03-11" = "Off", "2022-03-13" = "Off", "2022-03-15" = "Off", "2022-03-17" = "Off", "2022-03-18" = "Off", "2022-03-19" = "Off", "2022-03-21" = "Off", "2022-03-24" = "Off", "2022-03-26" = "Off", "2022-03-29" = "Off", "2022-03-31" = "Off", "2022-04-01" = "Off", "2022-04-04" = "Off", "2022-04-05" = "Off", "2022-04-06" = "Off", "2022-04-08" = "Off", "2022-04-11" = "Off", "2022-04-12" = "Off", "2022-04-13" = "Off", "2022-04-14" = "Off", "2022-04-15" = "Off", "2022-04-17" = "Off", "2022-04-19" = "Off", "2022-04-20" = "Off", "2022-04-22" = "Off", "2022-04-23" = "Off", "2022-04-25" = "Off", "2022-04-26" = "Off", "2022-04-28" = "Off", "2022-04-29" = "Off", "2022-04-30" = "Off", "2022-05-02" = "Off", "2022-05-04" = "Off", "2022-05-05" = "Off", "2022-05-06" = "Off", "2022-05-08" = "Off", "2022-05-10" = "Off", "2022-05-12" = "Off", "2022-05-14" = "Off", "2022-05-15" = "Off", "2022-05-16" = "Off", "2022-05-17" = "Off", "2022-05-19" = "Off", "2022-05-21" = "Off", "2022-05-23" = "Off", "2022-05-25" = "Off", "2022-05-27" = "Off", "2022-05-28" = "Off", "2022-05-29" = "Off", "2022-05-30" = "Off", "2022-05-31" = "Off", "2022-06-01" = "Off", "2022-06-03" = "Off", "2022-06-04" = "Off", "2022-06-06" = "Off", "2022-06-07" = "Off", "2022-06-09" = "Off", "2022-06-11" = "Off", "2022-06-12" = "Off", "2022-06-14" = "Off", "2022-06-15" = "Off", "2022-06-17" = "Off", "2022-06-18" = "Off", "2022-06-19" = "Off", "2022-06-20" = "Off")    
                         
d_season2 <- subset(d_season, outcome == "Win" | outcome == "Loss")

```

```{r adding a column for regular/post season}

d_season2$season <- recode(d_season2$season, "2022-06-16" = "Playoff", "2022-06-13" = "Playoff", "2022-06-10" = "Playoff", "2022-06-05" = "Playoff", "2022-05-26" = "Playoff", "2022-05-22" = "Playoff", "2022-05-20" = "Playoff", "2022-05-18" = "Playoff", "2022-05-13" = "Playoff", "2022-05-09" = "Playoff", "2022-05-07" = "Playoff", "2022-05-01" = "Playoff", "2022-04-27" = "Playoff", "2022-04-21" = "Playoff", "2022-04-18" = "Playoff", "2022-04-16" = "Playoff", "2022-04-10" = "Regular", "2022-04-09" = "Regular", "2022-04-07" = "Regular", "2022-04-03" = "Regular", "2022-04-02" = "Regular", "2022-03-23" = "Regular", "2022-03-14" = "Regular", "2022-03-12" = "Regular", "2022-03-10" = "Regular", "2022-03-08" = "Regular", "2022-02-24" = "Regular", "2022-02-12" = "Regular", "2022-02-07" = "Regular", "2022-02-03" = "Regular", "2022-02-01" = "Regular", "2022-01-31" = "Regular", "2022-01-29" = "Regular", "2022-01-27" = "Regular", "2022-01-25" = "Regular", "2022-01-23" = "Regular", "2022-01-21" = "Regular", "2022-01-18" = "Regular", "2022-01-14" = "Regular", "2022-01-09" = "Regular", "2022-01-03" = "Regular", "2022-01-01" = "Regular", "2021-12-25" = "Regular", "2021-12-23" = "Regular", "2021-12-20" = "Regular", "2021-12-17" = "Regular", "2021-12-14" = "Regular", "2021-12-13" = "Regular", "2021-12-08" = "Regular", "2021-12-06" = "Regular", "2021-12-03" = "Regular", "2021-11-28" = "Regular", "2021-11-26" = "Regular", "2021-11-24" = "Regular", "2021-11-21" = "Regular", "2021-11-19" = "Regular", "2021-11-18" = "Regular", "2021-11-16" = "Regular", "2021-11-12" = "Regular", "2021-11-10" = "Regular", "2021-11-08" = "Regular", "2021-11-07" = "Regular", "2021-11-05" = "Regular", "2021-11-03" = "Regular", "2021-10-30" = "Regular", "2021-10-26" = "Regular", "2021-10-24" = "Regular", "2021-10-21" = "Regular", "2021-10-19" = "Regular")

d_season2$season <- recode(d_season2$season, "2022-06-08" = "Playoff", "2022-06-02" = "Playoff", "2022-05-24" = "Playoff", "2022-05-11" = "Playoff", "2022-05-03" = "Playoff","2022-04-24" = "Playoff", "2022-03-30" = "Regular", "2022-03-28" = "Regular", "2022-03-27" = "Regular", "2022-03-25" = "Regular", "2022-03-22" = "Regular", "2022-03-20" = "Regular", "2022-03-16" = "Regular", "2022-03-07" = "Regular", "2022-03-05" = "Regular", "2022-03-03" = "Regular", "2022-03-01" = "Regular", "2022-02-27" = "Regular", "2022-02-16" = "Regular", "2022-02-14" = "Regular", "2022-02-10" = "Regular", "2022-02-09" = "Regular", "2022-01-20" = "Regular", "2022-01-16" = "Regular", "2022-01-13" = "Regular", "2022-01-11" = "Regular", "2022-01-06" = "Regular", "2022-01-05" = "Regular", "2021-12-28" = "Regular", "2021-12-18" = "Regular", "2021-12-11" = "Regular", "2021-12-04" = "Regular", "2021-11-30" = "Regular", "2021-11-14" = "Regular", "2021-10-28" = "Regular") 
```

```{r adding wins and losses to the playoffs}
# adding wins and losses to the dataset?
d_playoffs$outcome <- as.character(d_playoffs$day)
#d_season$outcome <- recode(d_season$outcome, "2022-06-19" = "Off","2022-06-18" = "Off", #"2022-06-17" = "Off","2022-06-15" = "Off", "2022-06-14" = "Off", )
d_playoffs$outcome <- recode(d_playoffs$outcome, "2022-06-16" = "Win", "2022-06-13" = "Win", "2022-06-10" = "Win", "2022-06-05" = "Win", "2022-05-26" = "Win", "2022-05-22" = "Win", "2022-05-20" = "Win", "2022-05-18" = "Win", "2022-05-13" = "Win", "2022-05-09" = "Win", "2022-05-07" = "Win", "2022-05-01" = "Win", "2022-04-27" = "Win", "2022-04-21" = "Win", "2022-04-18" = "Win", "2022-04-16" = "Win")

d_playoffs$outcome <- recode(d_playoffs$outcome, "2022-06-08" = "Loss", "2022-06-02" = "Loss", "2022-05-24" = "Loss", "2022-05-11" = "Loss", "2022-05-03" = "Loss","2022-04-24" = "Loss") 

d_playoffs$outcome <- recode(d_playoffs$outcome, "2022-04-17" = "Off", "2022-04-19" = "Off", "2022-04-20" = "Off", "2022-04-22" = "Off", "2022-04-23" = "Off", "2022-04-25" = "Off", "2022-04-26" = "Off", "2022-04-28" = "Off", "2022-04-29" = "Off", "2022-04-30" = "Off", "2022-05-02" = "Off", "2022-05-04" = "Off", "2022-05-05" = "Off", "2022-05-06" = "Off", "2022-05-08" = "Off", "2022-05-10" = "Off", "2022-05-12" = "Off", "2022-05-14" = "Off", "2022-05-15" = "Off", "2022-05-16" = "Off", "2022-05-17" = "Off", "2022-05-19" = "Off", "2022-05-21" = "Off", "2022-05-23" = "Off", "2022-05-25" = "Off", "2022-05-27" = "Off", "2022-05-28" = "Off", "2022-05-29" = "Off", "2022-05-30" = "Off", "2022-05-31" = "Off", "2022-06-01" = "Off", "2022-06-03" = "Off", "2022-06-04" = "Off", "2022-06-06" = "Off", "2022-06-07" = "Off", "2022-06-09" = "Off", "2022-06-11" = "Off", "2022-06-12" = "Off", "2022-06-14" = "Off", "2022-06-15" = "Off", "2022-06-17" = "Off", "2022-06-18" = "Off", "2022-06-19" = "Off", "2022-06-20" = "Off")  

d_playoffs2 <- subset(d_playoffs, outcome == "Win" | outcome == "Loss")

```

```{r warriors analytic thinking}

ggplot(d_season2, aes(x=day, y=Analytic, color=outcome)) +
  geom_smooth(stat = "summary", fun = "mean") +
  stat_smooth(span = .5, alpha = .2) +
  theme_minimal() +
  scale_color_manual(values = c("#006BB8", "#FDBA21")) +
  labs(x = "2021-2022 NBA Season - Warriors")

ggplot(data = d_season2, mapping = aes(x = outcome, y = Analytic, color = outcome)) + 
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#006BB8", "#FDBA21")) +
  labs(x = "Outcome")


ggboxplot(d_season2, x = "season", y = "Analytic", color = "outcome",
          palette = c("#006BB8", "#FDBA21")) +
  theme_minimal() +
    labs(x = "Season")


d_season2 %>% 
  group_by(outcome) %>% 
  summarize(meanAnalytic = mean(Analytic),
            sd_Analytic = sd(Analytic))

a_Analytic1 <- aov(Analytic ~ outcome + season, data = d_season2) 
summary(a_Analytic1)

a_Analytic2 <- aov(Analytic ~ outcome + season + outcome*season, data = d_season2) 
summary(a_Analytic2)

```

```{r warriors cogproc thinking}
ggplot(d_season2, aes(x=day, y=cogproc, color=outcome)) +
  geom_smooth(stat = "summary", fun = "mean") +
  stat_smooth(span = .5, alpha = .2) +
  theme_minimal() +
  scale_color_manual(values = c("#006BB8", "#FDBA21")) +
  labs(x = "2021-2022 NBA Season - Warriors")


ggplot(data = d_season2, mapping = aes(x = outcome, y = cogproc, color = outcome)) + 
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#006BB8", "#FDBA21")) +
    labs(x = "Outcome")


ggboxplot(d_season2, x = "season", y = "cogproc", color = "outcome", palette = c("#006BB8", "#FDBA21")) +
  theme_minimal() +
    labs(x = "Season") 

d_season2 %>% 
  group_by(outcome) %>% 
  summarize(meancogproc = mean(cogproc),
            sd_cogproc = sd(cogproc))

a_cogproc1 <- aov(cogproc ~ outcome + season, data = d_season2) 
summary(a_cogproc1)

a_cogproc2 <- aov(cogproc ~ outcome + season + outcome*season, data = d_season2) 
summary(a_cogproc2)

```


```{r warriors anxious emotions}
ggplot(d_season2, aes(x=day, y=emo_anx, color=outcome)) +
  geom_smooth(stat = "summary", fun = "mean") +
  theme_minimal() +
  scale_color_manual(values = c("#006BB8", "#FDBA21"))

ggplot(data = d_season2, mapping = aes(x = outcome, y = emo_anx, color = outcome)) + 
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#006BB8", "#FDBA21"))

ggboxplot(d_season2, x = "season", y = "emo_anx", color = "outcome",
          palette = c("#006BB8", "#FDBA21")) +
  theme_minimal()

d_season2 %>% 
  group_by(outcome) %>% 
  summarize(meanemo_anx = mean(emo_anx),
            sd_emo_anx = sd(emo_anx))

a_emo_anx1 <- aov(emo_anx ~ outcome + season, data = d_season2) 
summary(a_emo_anx1)

a_emo_anx2 <- aov(emo_anx ~ outcome + season + outcome*season, data = d_season2) 
summary(a_emo_anx2)

```

```{r warriors we words, fig.width=10,fig.height= 4}
ggplot(d_season, aes(x=day, y=we, color=outcome)) +
  geom_smooth(stat = "summary", fun = "mean") +
  theme_minimal() +
  scale_color_manual(values = c("#006BB8", "gray", "#FDBA21"))

ggplot(data = d_season, mapping = aes(x = outcome, y = we, color = outcome)) + 
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#006BB8", "gray", "#FDBA21"))

d_season %>% 
  group_by(outcome) %>% 
  summarize(meanwe = mean(we),
            sd_we = sd(we))

a_we1 <- aov(we ~ outcome, data = d_season) 
summary(a_we1)

```
```{r warriors i words, fig.width=10,fig.height= 4}
ggplot(d_season, aes(x=day, y=i, color=outcome)) +
  geom_smooth(stat = "summary", fun = "mean") +
  theme_minimal() +
  scale_color_manual(values = c("#006BB8", "gray", "#FDBA21"))

ggplot(data = d_season, mapping = aes(x = outcome, y = i, color = outcome)) + 
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#006BB8", "gray", "#FDBA21"))

d_season %>% 
  group_by(outcome) %>% 
  summarize(meani = mean(i),
            sd_i = sd(i))

a_i1 <- aov(i ~ outcome, data = d_season) 
summary(a_i1)

```

```{r warriors positive emotions}
ggplot(d_season2, aes(x=day, y=emo_pos, color=outcome)) +
  geom_smooth(stat = "summary", fun = "mean") +
  theme_minimal() +
  scale_color_manual(values = c("#006BB8", "#FDBA21"))

ggplot(data = d_season2, mapping = aes(x = outcome, y = emo_pos, color = outcome)) + 
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#006BB8", "#FDBA21"))

ggboxplot(d_season2, x = "season", y = "emo_pos", color = "outcome",
          palette = c("#006BB8", "#FDBA21")) +
  theme_minimal()

d_season2 %>% 
  group_by(outcome) %>% 
  summarize(meanemo_pos = mean(emo_pos),
            sd_emo_pos = sd(emo_pos))

a_emo_pos1 <- aov(emo_pos ~ outcome + season, data = d_season2) 
summary(a_emo_pos1)

a_emo_pos2 <- aov(emo_pos ~ outcome + season + outcome*season, data = d_season2) 
summary(a_emo_pos2)

```
```{r warriors negative emotions}
ggplot(d_season2, aes(x=day, y=emo_neg, color=outcome)) +
  geom_smooth(stat = "summary", fun = "mean") +
  theme_minimal() +
  scale_color_manual(values = c("#006BB8", "#FDBA21"))

ggplot(data = d_season2, mapping = aes(x = outcome, y = emo_neg, color = outcome)) + 
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#006BB8", "#FDBA21"))

ggboxplot(d_season2, x = "season", y = "emo_neg", color = "outcome",
          palette = c("#006BB8", "#FDBA21")) +
  theme_minimal()

d_season2 %>% 
  group_by(outcome) %>% 
  summarize(meanemo_neg = mean(emo_neg),
            sd_emo_neg = sd(emo_neg))

a_emo_neg1 <- aov(emo_neg ~ outcome + season, data = d_season2) 
summary(a_emo_neg1)

a_emo_neg2 <- aov(emo_neg ~ outcome + season + outcome*season, data = d_season2) 
summary(a_emo_neg2)

```

```{r, fig.width=10,fig.height= 2}
#creating my own dataframe

record <- data.frame(name= c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104))

record$outcomes <- c("W", "W", "W", "W", "L", "W", "W", "W", "W", "W", "W", "W", "L", "W", "W", "W", "W", "W", "W", "W", "L", "W", "L", "W", "W", "L", "W", "W", "W", "L", "W", "W", "W", "L", "W", "W", "L", "L", "W", "L", "L", "W", "L", "W", "L", "W", "W", "W", "W", "W", "W", "W", "W", "W", "L", "L", "W", "L", "L", "W", "L", "L", "L", "L", "L", "W", "W", "W", "W", "L", "L", "L", "W", "L", "L", "L", "L", "W", "W", "W", "W", "W", "W", "W", "W", "L", "W", "W", "L", "W", "W", "L", "W", "W", "W", "W", "L", "W", "L", "W", "L", "W", "W", "W")

ggplot(record,aes(x = name, fill=outcomes)) + 
	geom_bar(position = 'stack', stat = 'count') + 
  theme_minimal() +
  scale_fill_manual(values = c("#006BB8", "#FDBA21")) +
  labs(x = "2021-2022 NBA Season - Warriors") +
  theme(axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank()  #remove y axis ticks
        ) +
  geom_vline(xintercept=c(83), linetype=4)

```
